package control;


import javax.swing.JSlider;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marco
 */
public class GUI extends javax.swing.JFrame {
	
	Controller controller = new Controller();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	jSlider1 = new javax.swing.JSlider();
        arousal = new javax.swing.JPanel();
        intensity = new javax.swing.JSlider();
        strength = new javax.swing.JSlider();
        tempo = new javax.swing.JSlider();
        intensityValueLabel = new javax.swing.JLabel();
        tempoValueLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        strengthValueLabel = new javax.swing.JLabel();
        valence = new javax.swing.JPanel();
        timbre = new javax.swing.JSlider();
        irregularity = new javax.swing.JSlider();
        dissonances = new javax.swing.JSlider();
        timbreValueLabel = new javax.swing.JLabel();
        dissonancesValueLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        irregularityValueLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        shaper2A = new javax.swing.JSlider();
        jLabel24 = new javax.swing.JLabel();
        shaper3A = new javax.swing.JSlider();
        shaper4A = new javax.swing.JSlider();
        attackA = new javax.swing.JTextField();
        shaper5A = new javax.swing.JSlider();
        vibratoA = new javax.swing.JTextField();
        decayA = new javax.swing.JTextField();
        shaper6A = new javax.swing.JSlider();
        mixOrigA = new javax.swing.JTextField();
        shaper7A = new javax.swing.JSlider();
        mixCheby3A = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        mixCheby4A = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        shaper0A = new javax.swing.JSlider();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        shaper1A = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        shaper2B = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        shaper3B = new javax.swing.JSlider();
        shaper4B = new javax.swing.JSlider();
        attackB = new javax.swing.JTextField();
        shaper5B = new javax.swing.JSlider();
        vibratoB = new javax.swing.JTextField();
        decayB = new javax.swing.JTextField();
        shaper6B = new javax.swing.JSlider();
        mixOrigB = new javax.swing.JTextField();
        shaper7B = new javax.swing.JSlider();
        mixCheby3B = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mixCheby4B = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        shaper0B = new javax.swing.JSlider();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        shaper1B = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        vibratoM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        attackM = new javax.swing.JTextField();
        decayM = new javax.swing.JTextField();
        mixOrigM = new javax.swing.JTextField();
        mixCheby3M = new javax.swing.JTextField();
        mixCheby4M = new javax.swing.JTextField();
        shaper0M = new javax.swing.JSlider();
        shaper1M = new javax.swing.JSlider();
        shaper2M = new javax.swing.JSlider();
        shaper3M = new javax.swing.JSlider();
        shaper4M = new javax.swing.JSlider();
        shaper5M = new javax.swing.JSlider();
        shaper6M = new javax.swing.JSlider();
        shaper7M = new javax.swing.JSlider();
        jLabel15 = new javax.swing.JLabel();
        changeButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        mixerM = new javax.swing.JSlider();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        MixerA = new javax.swing.JSlider();
        jLabel33 = new javax.swing.JLabel();
        MixerB = new javax.swing.JSlider();
        jLabel34 = new javax.swing.JLabel();
        mixerMaster = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arousal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        arousal.setName(""); // NOI18N

        intensity.setToolTipText("");
        intensity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        intensity.setName("Timbre"); // NOI18N
        intensity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intensityStateChanged(evt);
            }
        });

        strength.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                strengthStateChanged(evt);
            }
        });

        tempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tempoStateChanged(evt);
            }
        });

        intensityValueLabel.setText("0");

        tempoValueLabel.setText("0");

        jLabel8.setText("Intensity");

        jLabel9.setText("Rhythm strength");

        jLabel10.setText("Tempo");

        jLabel11.setText("Arousal Parameters");

        strengthValueLabel.setText("0");

        javax.swing.GroupLayout arousalLayout = new javax.swing.GroupLayout(arousal);
        arousal.setLayout(arousalLayout);
        arousalLayout.setHorizontalGroup(
            arousalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arousalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(arousalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(arousalLayout.createSequentialGroup()
                        .addComponent(intensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intensityValueLabel))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(arousalLayout.createSequentialGroup()
                        .addComponent(strength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(strengthValueLabel))
                    .addGroup(arousalLayout.createSequentialGroup()
                        .addComponent(tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempoValueLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        arousalLayout.setVerticalGroup(
            arousalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(arousalLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(arousalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intensityValueLabel))
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(arousalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strengthValueLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(arousalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempoValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        valence.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        valence.setName(""); // NOI18N

        timbre.setToolTipText("");
        timbre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        timbre.setName("Timbre"); // NOI18N
        timbre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timbreStateChanged(evt);
            }
        });

        irregularity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                irregularityStateChanged(evt);
            }
        });

        dissonances.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dissonancesStateChanged(evt);
            }
        });

        timbreValueLabel.setText("0");

        dissonancesValueLabel.setText("0");

        jLabel4.setText("Timbre");

        jLabel5.setText("Irregularity");

        jLabel6.setText("Dissonances (not working)");

        jLabel7.setText("Valence Parameters");

        irregularityValueLabel.setText("0");

        javax.swing.GroupLayout valenceLayout = new javax.swing.GroupLayout(valence);
        valence.setLayout(valenceLayout);
        valenceLayout.setHorizontalGroup(
            valenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(valenceLayout.createSequentialGroup()
                        .addComponent(timbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timbreValueLabel))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(valenceLayout.createSequentialGroup()
                        .addComponent(irregularity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(irregularityValueLabel))
                    .addGroup(valenceLayout.createSequentialGroup()
                        .addComponent(dissonances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dissonancesValueLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        valenceLayout.setVerticalGroup(
            valenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valenceLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timbreValueLabel))
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(irregularity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(irregularityValueLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(valenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dissonances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dissonancesValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setText("3rd Chebyshev Polynomal mix (0-1)");

        shaper2A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper2A.setValue((int) (controller.player.accompaniment.synth.shaper[2]*100));
        shaper2A.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper2AStateChanged(evt);
            }
        });

        jLabel24.setText("4rd Chebyshev Polynomal mix (0-1)");

        shaper3A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper3A.setValue((int) (controller.player.accompaniment.synth.shaper[3]*100));
        shaper3A.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper3AStateChanged(evt);
            }
        });

        shaper4A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper4A.setValue((int) (controller.player.accompaniment.synth.shaper[4]*100));
        shaper4A.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper4AStateChanged(evt);
            }
        });

        attackA.setColumns(6);
        attackA.setText(String.valueOf(controller.player.accompaniment.synth.attack));
        attackA.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        attackA.setMinimumSize(new java.awt.Dimension(59, 20));
        attackA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackAActionPerformed(evt);
            }
        });

        shaper5A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper5A.setValue((int) (controller.player.accompaniment.synth.shaper[5]*100));
        shaper5A.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper5APropertyChange(evt);
            }
        });

        vibratoA.setColumns(6);
        vibratoA.setText(String.valueOf(controller.player.accompaniment.synth.vibrato));
        vibratoA.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        vibratoA.setMinimumSize(new java.awt.Dimension(59, 20));
        vibratoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibratoAActionPerformed(evt);
            }
        });

        decayA.setColumns(6);
        decayA.setText(String.valueOf(controller.player.accompaniment.synth.decay));
        decayA.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        decayA.setMinimumSize(new java.awt.Dimension(59, 20));
        decayA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decayAActionPerformed(evt);
            }
        });

        shaper6A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper6A.setValue((int) (controller.player.accompaniment.synth.shaper[6]*100));
        shaper6A.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper6APropertyChange(evt);
            }
        });

        mixOrigA.setColumns(6);
        mixOrigA.setText(String.valueOf(controller.player.accompaniment.synth.mixOriginal));
        mixOrigA.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixOrigA.setMinimumSize(new java.awt.Dimension(59, 20));
        mixOrigA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixOrigAActionPerformed(evt);
            }
        });

        shaper7A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper7A.setValue((int) (controller.player.accompaniment.synth.shaper[7]*100));
        shaper7A.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper7APropertyChange(evt);
            }
        });

        mixCheby3A.setColumns(6);
        mixCheby3A.setText(String.valueOf(controller.player.accompaniment.synth.mixCheby3));
        mixCheby3A.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixCheby3A.setMinimumSize(new java.awt.Dimension(59, 20));
        mixCheby3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixCheby3AActionPerformed(evt);
            }
        });

        jLabel25.setText("Vibrato (0-1)");

        jLabel26.setText("Shaper");

        mixCheby4A.setColumns(6);
        mixCheby4A.setText(String.valueOf(controller.player.accompaniment.synth.mixCheby4));
        mixCheby4A.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixCheby4A.setMinimumSize(new java.awt.Dimension(59, 20));
        mixCheby4A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixCheby4AActionPerformed(evt);
            }
        });

        jLabel27.setText("Attack (ms)");

        shaper0A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper0A.setValue((int) (controller.player.accompaniment.synth.shaper[0]*100));
        shaper0A.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper0AStateChanged(evt);
            }
        });

        jLabel28.setText("Decay (ms)");

        jLabel29.setText("Original Mix (0-1)");

        shaper1A.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper1A.setValue((int) (controller.player.accompaniment.synth.shaper[1]*100));
        shaper1A.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper1AStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(vibratoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(attackA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(decayA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixOrigA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixCheby3A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixCheby4A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shaper0A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper1A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper2A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper3A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper4A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper5A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper6A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper7A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vibratoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel29))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(attackA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(decayA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mixOrigA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mixCheby4A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mixCheby3A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(shaper0A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper1A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper2A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper3A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper4A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper5A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper6A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper7A, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Accompaniment", jPanel2);

        jLabel16.setText("3rd Chebyshev Polynomal mix (0-1)");

        shaper2B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper2B.setValue((int) (controller.player.bass.synth.shaper[2]*100));
        shaper2B.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper2BStateChanged(evt);
            }
        });

        jLabel17.setText("4rd Chebyshev Polynomal mix (0-1)");

        shaper3B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper3B.setValue((int) (controller.player.bass.synth.shaper[3]*100));
        shaper3B.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper3BStateChanged(evt);
            }
        });

        shaper4B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper4B.setValue((int) (controller.player.bass.synth.shaper[4]*100));
        shaper4B.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper4BStateChanged(evt);
            }
        });

        attackB.setColumns(6);
        attackB.setText(String.valueOf(controller.player.bass.synth.attack));
        attackB.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        attackB.setMinimumSize(new java.awt.Dimension(59, 20));
        attackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackBActionPerformed(evt);
            }
        });

        shaper5B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper5B.setValue((int) (controller.player.bass.synth.shaper[5]*100));
        shaper5B.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper5BPropertyChange(evt);
            }
        });

        vibratoB.setColumns(6);
        vibratoB.setText(String.valueOf(controller.player.bass.synth.vibrato));
        vibratoB.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        vibratoB.setMinimumSize(new java.awt.Dimension(59, 20));
        vibratoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibratoBActionPerformed(evt);
            }
        });

        decayB.setColumns(6);
        decayB.setText(String.valueOf(controller.player.bass.synth.decay));
        decayB.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        decayB.setMinimumSize(new java.awt.Dimension(59, 20));
        decayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decayBActionPerformed(evt);
            }
        });

        shaper6B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper6B.setValue((int) (controller.player.bass.synth.shaper[6]*100));
        shaper6B.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper6BPropertyChange(evt);
            }
        });

        mixOrigB.setColumns(6);
        mixOrigB.setText(String.valueOf(controller.player.bass.synth.mixOriginal));
        mixOrigB.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixOrigB.setMinimumSize(new java.awt.Dimension(59, 20));
        mixOrigB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixOrigBActionPerformed(evt);
            }
        });

        shaper7B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper7B.setValue((int) (controller.player.bass.synth.shaper[7]*100));
        shaper7B.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper7BPropertyChange(evt);
            }
        });

        mixCheby3B.setColumns(6);
        mixCheby3B.setText(String.valueOf(controller.player.bass.synth.mixCheby3));
        mixCheby3B.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixCheby3B.setMinimumSize(new java.awt.Dimension(59, 20));
        mixCheby3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixCheby3BActionPerformed(evt);
            }
        });

        jLabel18.setText("Vibrato (0-1)");

        jLabel19.setText("Shaper");

        mixCheby4B.setColumns(6);
        mixCheby4B.setText(String.valueOf(controller.player.bass.synth.mixCheby4));
        mixCheby4B.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixCheby4B.setMinimumSize(new java.awt.Dimension(59, 20));
        mixCheby4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixCheby4BActionPerformed(evt);
            }
        });

        jLabel20.setText("Attack (ms)");

        shaper0B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper0B.setValue((int) (controller.player.bass.synth.shaper[0]*100));
        shaper0B.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper0BStateChanged(evt);
            }
        });

        jLabel21.setText("Decay (ms)");

        jLabel22.setText("Original Mix (0-1)");

        shaper1B.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper1B.setValue((int) (controller.player.bass.synth.shaper[1]*100));
        shaper1B.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper1BStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(vibratoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(attackB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(decayB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixOrigB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixCheby3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixCheby4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shaper0B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper2B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper5B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper6B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper7B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vibratoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(attackB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(decayB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mixOrigB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mixCheby4B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mixCheby3B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(shaper0B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper1B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper2B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper3B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper4B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper5B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper6B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper7B, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bass", jPanel3);

        vibratoM.setColumns(6);
        vibratoM.setText(String.valueOf(controller.player.melody.synth.vibrato));
        vibratoM.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        vibratoM.setMinimumSize(new java.awt.Dimension(59, 20));
        vibratoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibratoMActionPerformed(evt);
            }
        });

        jLabel1.setText("Vibrato (0-1)");

        jLabel2.setText("Attack (ms)");

        jLabel3.setText("Decay (ms)");

        jLabel12.setText("Original Mix (0-1)");

        jLabel13.setText("3rd Chebyshev Polynomal mix (0-1)");

        jLabel14.setText("4rd Chebyshev Polynomal mix (0-1)");

        attackM.setColumns(6);
        attackM.setText(String.valueOf(controller.player.melody.synth.attack));
        attackM.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        attackM.setMinimumSize(new java.awt.Dimension(59, 20));
        attackM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackMActionPerformed(evt);
            }
        });

        decayM.setColumns(6);
        decayM.setText(String.valueOf(controller.player.melody.synth.decay));
        decayM.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        decayM.setMinimumSize(new java.awt.Dimension(59, 20));
        decayM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decayMActionPerformed(evt);
            }
        });

        mixOrigM.setColumns(6);
        mixOrigM.setText(String.valueOf(controller.player.melody.synth.mixOriginal));
        mixOrigM.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixOrigM.setMinimumSize(new java.awt.Dimension(59, 20));
        mixOrigM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixOrigMActionPerformed(evt);
            }
        });

        mixCheby3M.setColumns(6);
        mixCheby3M.setText(String.valueOf(controller.player.melody.synth.mixCheby3));
        mixCheby3M.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixCheby3M.setMinimumSize(new java.awt.Dimension(59, 20));
        mixCheby3M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixCheby3MActionPerformed(evt);
            }
        });

        mixCheby4M.setColumns(6);
        mixCheby4M.setText(String.valueOf(controller.player.melody.synth.mixCheby4));
        mixCheby4M.setMaximumSize(new java.awt.Dimension(59, 2147483647));
        mixCheby4M.setMinimumSize(new java.awt.Dimension(59, 20));
        mixCheby4M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixCheby4MActionPerformed(evt);
            }
        });

        shaper0M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper0M.setValue((int) (controller.player.melody.synth.shaper[0]*100));
        shaper0M.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper0MStateChanged(evt);
            }
        });

        shaper1M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper1M.setValue((int) (controller.player.melody.synth.shaper[1]*100));
        shaper1M.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper1MStateChanged(evt);
            }
        });

        shaper2M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper2M.setValue((int) (controller.player.melody.synth.shaper[2]*100));
        shaper2M.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper2MStateChanged(evt);
            }
        });

        shaper3M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper3M.setValue((int) (controller.player.melody.synth.shaper[3]*100));
        shaper3M.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper3MStateChanged(evt);
            }
        });

        shaper4M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper4M.setValue((int) (controller.player.melody.synth.shaper[4]*100));
        shaper4M.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shaper4MStateChanged(evt);
            }
        });

        shaper5M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper5M.setValue((int) (controller.player.melody.synth.shaper[5]*100));
        shaper5M.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper5MPropertyChange(evt);
            }
        });

        shaper6M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper6M.setValue((int) (controller.player.melody.synth.shaper[6]*100));
        shaper6M.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper6MPropertyChange(evt);
            }
        });

        shaper7M.setOrientation(javax.swing.JSlider.VERTICAL);
        shaper7M.setValue((int) (controller.player.melody.synth.shaper[7]*100));
        shaper7M.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                shaper7MPropertyChange(evt);
            }
        });

        jLabel15.setText("Shaper");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(vibratoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(attackM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(decayM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixOrigM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixCheby3M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mixCheby4M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shaper0M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper1M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper2M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper3M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper4M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper5M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper6M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shaper7M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vibratoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(attackM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(decayM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mixOrigM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mixCheby4M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mixCheby3M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addComponent(shaper0M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper1M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper2M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper3M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper4M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper5M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper6M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shaper7M, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("Attack");

        jTabbedPane1.addTab("Melody", jPanel1);

        changeButton.setText("Change Composition");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        jLabel30.setText("Mixer");

        mixerM.setValue((int) (controller.player.mixer.melMix*100));
        mixerM.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mixerMStateChanged(evt);
            }
        });

        jLabel31.setText("Melody");

        jLabel32.setText("Accompaniment");

        MixerA.setValue((int) (controller.player.mixer.accMix*100));
        MixerA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MixerAStateChanged(evt);
            }
        });

        jLabel33.setText("Bass");

        MixerB.setValue((int) (controller.player.mixer.bassMix*100));
        MixerB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MixerBStateChanged(evt);
            }
        });
        
        jLabel34.setText("Master");

        mixerMaster.setValue((int) (controller.player.mixer.masterMix*100)/5);
        mixerMaster.setOrientation(javax.swing.JSlider.VERTICAL);
        mixerMaster.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mixerMasterStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mixerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MixerA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MixerB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(mixerMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(mixerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(MixerA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MixerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(mixerMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arousal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(arousal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void timbreStateChanged(javax.swing.event.ChangeEvent evt) {                                    
        timbreValueLabel.setText(String.valueOf(timbre.getValue()));
        controller.setTimbre(timbre.getValue());
    }                                   

    private void irregularityStateChanged(javax.swing.event.ChangeEvent evt) {                                          
        irregularityValueLabel.setText(String.valueOf(irregularity.getValue()));
        controller.setIrregularity(irregularity.getValue());
    }                                         

    private void dissonancesStateChanged(javax.swing.event.ChangeEvent evt) {                                         
        dissonancesValueLabel.setText(String.valueOf(dissonances.getValue()));
        // WARN: need to activate
        controller.setDissonance(dissonances.getValue());
    }                                        

    private void intensityStateChanged(javax.swing.event.ChangeEvent evt) {                                       
        intensityValueLabel.setText(String.valueOf(intensity.getValue()));
        controller.setIntensity(intensity.getValue());
        updateMixer();
    }                                      

    private void strengthStateChanged(javax.swing.event.ChangeEvent evt) {                                      
        strengthValueLabel.setText(String.valueOf(strength.getValue()));
        controller.setStrength(strength.getValue());
    }                                     

    private void tempoStateChanged(javax.swing.event.ChangeEvent evt) {                                   
        tempoValueLabel.setText(String.valueOf(tempo.getValue()));
        controller.setTempo(tempo.getValue());
    }                                  

    private void vibratoMActionPerformed(java.awt.event.ActionEvent evt) {                                         
        float value = Float.valueOf(vibratoM.getText());
        controller.player.melody.synth.vibrato = value;
    }                                        

    private void attackMActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	float value = Float.valueOf(attackM.getText());
        controller.player.melody.synth.attack = value;
    }                                       

    private void decayMActionPerformed(java.awt.event.ActionEvent evt) {                                       
    	float value = Float.valueOf(decayM.getText());
        controller.player.melody.synth.decay = value;
    }                                      

    private void mixOrigMActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	float value = Float.valueOf(mixOrigM.getText());
        controller.player.melody.synth.mixOriginal = value;
    }                                        

    private void mixCheby3MActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	float value = Float.valueOf(mixCheby3M.getText());
        controller.player.melody.synth.mixCheby3 = value;
    }                                          

    private void mixCheby4MActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	float value = Float.valueOf(mixCheby4M.getText());
        controller.player.melody.synth.mixCheby4 = value;
    }                                          

    private void shaper0MStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper0M.getValue()/100;
        controller.player.melody.synth.shaper[0] = value;
    }                                     

    private void shaper1MStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper1M.getValue()/100;
        controller.player.melody.synth.shaper[1] = value;
    }                                     

    private void shaper2MStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper2M.getValue()/100;
        controller.player.melody.synth.shaper[2] = value;
    }                                     

    private void shaper3MStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper3M.getValue()/100;
        controller.player.melody.synth.shaper[3] = value;
    }                                     

    private void shaper4MStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper4M.getValue()/100;
        controller.player.melody.synth.shaper[4] = value;
    }                                     

    private void shaper5MPropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper5M.getValue()/100;
        controller.player.melody.synth.shaper[5] = value;
    }                                       

    private void shaper6MPropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper6M.getValue()/100;
        controller.player.melody.synth.shaper[6] = value;
    }                                       

    private void shaper7MPropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper7M.getValue()/100;
        controller.player.melody.synth.shaper[7] = value;
    }                                       

    private void shaper2BStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper2B.getValue()/100;
        controller.player.bass.synth.shaper[2] = value;
    }                                     

    private void shaper3BStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper3B.getValue()/100;
        controller.player.bass.synth.shaper[3] = value;
    }                                     

    private void shaper4BStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper4B.getValue()/100;
        controller.player.bass.synth.shaper[4] = value;
    }                                     

    private void attackBActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	float value = Float.valueOf(attackB.getText());
        controller.player.bass.synth.attack = value;
    }                                       

    private void shaper5BPropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper5B.getValue()/100;
        controller.player.bass.synth.shaper[5] = value;
    }                                       

    private void vibratoBActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	float value = Float.valueOf(vibratoB.getText());
        controller.player.bass.synth.vibrato = value;
    }                                        

    private void decayBActionPerformed(java.awt.event.ActionEvent evt) {                                       
    	float value = Float.valueOf(decayB.getText());
        controller.player.bass.synth.decay = value;
    }                                      

    private void shaper6BPropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper6B.getValue()/100;
        controller.player.bass.synth.shaper[6] = value;
    }                                       

    private void mixOrigBActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	float value = Float.valueOf(mixOrigB.getText());
        controller.player.bass.synth.mixOriginal = value;
    }                                        

    private void shaper7BPropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper7B.getValue()/100;
        controller.player.bass.synth.shaper[7] = value;
    }                                       

    private void mixCheby3BActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	float value = Float.valueOf(mixCheby3B.getText());
        controller.player.bass.synth.mixCheby3 = value;
    }                                          

    private void mixCheby4BActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	float value = Float.valueOf(mixCheby4B.getText());
        controller.player.bass.synth.mixCheby4 = value;
    }                                          

    private void shaper0BStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper0B.getValue()/100;
        controller.player.bass.synth.shaper[0] = value;
    }                                     

    private void shaper1BStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper1B.getValue()/100;
        controller.player.bass.synth.shaper[1] = value;
    }                                     

    private void shaper2AStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper2A.getValue()/100;
        controller.player.accompaniment.synth.shaper[2] = value;
    }                                     

    private void shaper3AStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper3A.getValue()/100;
        controller.player.accompaniment.synth.shaper[3] = value;
    }                                     

    private void shaper4AStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper4A.getValue()/100;
        controller.player.accompaniment.synth.shaper[4] = value;
    }                                     

    private void attackAActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	float value = Float.valueOf(attackA.getText());
        controller.player.accompaniment.synth.attack = value;
    }                                       

    private void shaper5APropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper5A.getValue()/100;
        controller.player.accompaniment.synth.shaper[5] = value;
    }                                       

    private void vibratoAActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	float value = Float.valueOf(vibratoA.getText());
        controller.player.accompaniment.synth.vibrato = value;
    }                                        

    private void decayAActionPerformed(java.awt.event.ActionEvent evt) {                                       
    	float value = Float.valueOf(decayA.getText());
        controller.player.accompaniment.synth.decay = value;
    }                                      

    private void shaper6APropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper6A.getValue()/100;
        controller.player.accompaniment.synth.shaper[6] = value;
    }                                       

    private void mixOrigAActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	float value = Float.valueOf(mixOrigA.getText());
        controller.player.accompaniment.synth.mixOriginal = value;
    }                                        

    private void shaper7APropertyChange(java.beans.PropertyChangeEvent evt) {                                        
    	float value = (float)shaper7A.getValue()/100;
        controller.player.accompaniment.synth.shaper[7] = value;
    }                                       

    private void mixCheby3AActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	float value = Float.valueOf(mixCheby3A.getText());
        controller.player.accompaniment.synth.mixCheby3 = value;
    }                                          

    private void mixCheby4AActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	float value = Float.valueOf(mixCheby4A.getText());
        controller.player.accompaniment.synth.mixCheby4 = value;
    }                                          

    private void shaper0AStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper0A.getValue()/100;
        controller.player.accompaniment.synth.shaper[0] = value;
    }                                     

    private void shaper1AStateChanged(javax.swing.event.ChangeEvent evt) {                                      
    	float value = (float)shaper1A.getValue()/100;
        controller.player.accompaniment.synth.shaper[1] = value;
    }                                     

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        controller.messageReceived(Command.CHANGE, null);
    }           
    
    private void mixerMStateChanged(javax.swing.event.ChangeEvent evt) {                                    
        controller.player.mixer.melMix = (float)mixerM.getValue()/100f;
        controller.player.mixer.updateVolumes();
    }                                   

    private void MixerAStateChanged(javax.swing.event.ChangeEvent evt) {                                    
    	controller.player.mixer.accMix = (float)MixerA.getValue()/100f;
        controller.player.mixer.updateVolumes();
    }                                   

    private void MixerBStateChanged(javax.swing.event.ChangeEvent evt) {                                    
    	controller.player.mixer.bassMix = (float)MixerB.getValue()/100f;
        controller.player.mixer.updateVolumes();
    }  
    
    private void mixerMasterStateChanged(javax.swing.event.ChangeEvent evt) {                                         
    	controller.player.mixer.masterMix = (float)mixerMaster.getValue()/100f * 5;
        controller.player.mixer.updateVolumes();
    }  
    
    private void updateMixer(){
    	mixerM.setValue((int) (controller.player.mixer.melMix*100));
    	MixerA.setValue((int) (controller.player.mixer.accMix*100));
    	MixerB.setValue((int) (controller.player.mixer.bassMix*100));
    	mixerMaster.setValue((int) (controller.player.mixer.masterMix*100)/5);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	GUI gui = new GUI();
                gui.setVisible(true);
                gui.controller.messageReceived(Command.START, null);
                gui.controller.messageReceived(Command.CHANGE, null);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JSlider MixerA;
    private javax.swing.JSlider MixerB;
    private javax.swing.JPanel arousal;
    private javax.swing.JTextField attackA;
    private javax.swing.JTextField attackB;
    private javax.swing.JTextField attackM;
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField decayA;
    private javax.swing.JTextField decayB;
    private javax.swing.JTextField decayM;
    private javax.swing.JSlider dissonances;
    private javax.swing.JLabel dissonancesValueLabel;
    private javax.swing.JSlider intensity;
    private javax.swing.JLabel intensityValueLabel;
    private javax.swing.JSlider irregularity;
    private javax.swing.JLabel irregularityValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mixCheby3A;
    private javax.swing.JTextField mixCheby3B;
    private javax.swing.JTextField mixCheby3M;
    private javax.swing.JTextField mixCheby4A;
    private javax.swing.JTextField mixCheby4B;
    private javax.swing.JTextField mixCheby4M;
    private javax.swing.JTextField mixOrigA;
    private javax.swing.JTextField mixOrigB;
    private javax.swing.JTextField mixOrigM;
    private javax.swing.JSlider mixerM;
    private javax.swing.JSlider mixerMaster;
    private javax.swing.JSlider shaper0A;
    private javax.swing.JSlider shaper0B;
    private javax.swing.JSlider shaper0M;
    private javax.swing.JSlider shaper1A;
    private javax.swing.JSlider shaper1B;
    private javax.swing.JSlider shaper1M;
    private javax.swing.JSlider shaper2A;
    private javax.swing.JSlider shaper2B;
    private javax.swing.JSlider shaper2M;
    private javax.swing.JSlider shaper3A;
    private javax.swing.JSlider shaper3B;
    private javax.swing.JSlider shaper3M;
    private javax.swing.JSlider shaper4A;
    private javax.swing.JSlider shaper4B;
    private javax.swing.JSlider shaper4M;
    private javax.swing.JSlider shaper5A;
    private javax.swing.JSlider shaper5B;
    private javax.swing.JSlider shaper5M;
    private javax.swing.JSlider shaper6A;
    private javax.swing.JSlider shaper6B;
    private javax.swing.JSlider shaper6M;
    private javax.swing.JSlider shaper7A;
    private javax.swing.JSlider shaper7B;
    private javax.swing.JSlider shaper7M;
    private javax.swing.JSlider strength;
    private javax.swing.JLabel strengthValueLabel;
    private javax.swing.JSlider tempo;
    private javax.swing.JLabel tempoValueLabel;
    private javax.swing.JSlider timbre;
    private javax.swing.JLabel timbreValueLabel;
    private javax.swing.JPanel valence;
    private javax.swing.JTextField vibratoA;
    private javax.swing.JTextField vibratoB;
    private javax.swing.JTextField vibratoM;
    // End of variables declaration                   
}
